# Setup
title:               John Wry
tagline:             '...Because memory does not serve me well'
description:         'Just a blog for all of my stuff'
url:                 https://johnwry.github.io
baseurl:             'blog/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              John Wry
  url:               https://thewrys.redbiblica.org
  email:             johnwry@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
